! Put your rules here in the format:
! old_biome > new_biome
!
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! terralith:lavender_forest > aurorasdeco:lavender_plains
! terralith:lavender_valley > aurorasdeco:lavender_plains
! terralith:cave/infested_caves > minecraft:dripstone_caves
terralith:alpha_islands_winter > terralith:alpha_islands
terralith:amethyst_canyon > terralith:caldera
terralith:amethyst_rainforest > terralith:temperate_highlands
terralith:basalt_cliffs > terralith:gravel_beach
terralith:cold_shrubland > minecraft:taiga
terralith:desert_spires > minecraft:desert
terralith:frozen_cliffs > terralith:white_cliffs
terralith:glacial_chasm > minecraft:stony_peaks
terralith:granite_cliffs > terralith:white_cliffs
terralith:gravel_desert > terralith:volcanic_crater
terralith:haze_mountain > terralith:rocky_mountains
terralith:ice_marsh > biomesoplenty:snowy_fir_clearing
terralith:lavender_forest > biomesoplenty:lavender_field
terralith:lavender_valley > biomesoplenty:lavender_field
terralith:lush_desert > biomesoplenty:lush_desert
terralith:mirage_isles > terralith:blooming_valley
terralith:moonlight_grove > terralith:siberian_grove
terralith:moonlight_valley > terralith:siberian_grove
terralith:orchid_swamp > biomesoplenty:dead_forest
terralith:painted_mountains > minecraft:badlands
terralith:sakura_grove > minecraft:cherry_grove
terralith:sakura_valley > minecraft:cherry_grove
terralith:skylands_autumn > minecraft:deep_ocean
terralith:skylands_spring > minecraft:deep_ocean
terralith:skylands_summer > minecraft:deep_ocean
terralith:skylands_winter > minecraft:deep_ocean
terralith:snowy_badlands > biomesoplenty:snowy_fir_clearing
terralith:stony_spires > biomesoplenty:snowy_coniferous_forest
terralith:tropical_jungle > biomesoplenty:jade_cliffs
terralith:valley_clearing > terralith:forested_highlands
terralith:warped_mesa > minecraft:badlands
terralith:windswept_spires > minecraft:eroded_badlands
terralith:yosemite_cliffs > terralith:yellowstone

terralith:cave/deep_caves > minecraft:dripstone_caves
terralith:cave/frostfire_caves > minecraft:lush_caves
terralith:cave/infested_caves > minecraft:dripstone_caves
terralith:cave/fungal_caves > minecraft:lush_caves
